version: "3.8"

networks:
  web-network:

volumes:
  data-volume:

services:
  web:
    depends_on:
      - db
    build:
      context: .
      dockerfile: docker/web
    container_name: azerfassung-web
    tty: true
    ports:
      - "80:8090"
    volumes:
      - ./:/var/www
    networks:
      - web-network
  db:
    image: mongo:latest
    container_name: azerfassung-db
    ports:
      - "27017:8091"
    volumes:
      - data-volume:/Volumes/Development/web/azerfassung/.mongo-data