version: "3.8"

volumes:
  data-volume:

networks:
  app-tier:
    driver: bridge

services:
  php-fpm:
    depends_on:
      - mongo
    build:
      context: ./php-fpm
    container_name: azerfassung-php-fpm
    volumes:
      - ../:/var/www
    ports:
      - "9000:9000"
    cgroup_parent: "azerfassung"
    networks:
      - app-tier

  nginx:
    depends_on:
      - php-fpm
    build:
      context: ./nginx
    container_name: azerfassung-nginx
    volumes:
      - ../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    ports:
      - "80:80"
    networks:
      - app-tier

  mongo:
    image: mongo:3.4
    ports:
      - 27017:27017
    restart: always
    container_name: app_mongodb_c
    volumes:
      - /Volumes/Development/web/azerfassung/.mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example